# Generated by Django 4.1.11 on 2023-09-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(default=None, upload_to='resume/'),
        ),
    ]
