# Generated by Django 4.1.11 on 2023-09-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_edu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edu',
        ),
    ]
