# Generated by Django 4.1.11 on 2023-09-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_edu'),
    ]

    operations = [
        migrations.CreateModel(
            name='edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField()),
                ('grade_choice', models.CharField(choices=[('CGPPA', 'CGPA'), ('PERCENTAGE', '%')], max_length=10)),
                ('grade', models.FloatField()),
            ],
        ),
    ]
