# Generated by Django 4.1.11 on 2023-09-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_edu_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='degree_link',
            field=models.FileField(default=None, upload_to='degree'),
        ),
    ]
