# Generated by Django 4.1.11 on 2023-09-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_edu_degree_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=60)),
                ('start_date', models.DateField()),
                ('still_working', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True)),
                ('total_exp', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
